import {CONFIG,PARAMS} from './config.js';import {World} from './world.js';import {Simulation} from './simulation.js';import {Renderer} from './renderer.js';
const canvas=document.querySelector('#world'),stage=document.querySelector('.stage');let world,sim,renderer,last=0;const cfg={...CONFIG};
function init(){let r=stage.getBoundingClientRect();world=new World(r.width,r.height,5); // seed obstacles
for(let y=r.height*.22;y<r.height*.75;y+=5)if(y<r.height*.43||y>r.height*.53)world.paint(r.width*.5,y,true,5);sim=new Simulation(world,cfg);renderer=new Renderer(canvas,world,sim);renderer.resize();}
function controls(){let box=document.querySelector('#controls');PARAMS.forEach(([k,n,min,max,step])=>{let d=document.createElement('div');d.className='controlRow';d.innerHTML=`<div class='controlTop'><span>${n}</span><b id='v-${k}'>${cfg[k]}</b></div><input id='p-${k}' type='range' min='${min}' max='${max}' step='${step}' value='${cfg[k]}'>`;box.append(d);d.querySelector('input').oninput=e=>{cfg[k]=+e.target.value;d.querySelector('b').textContent=cfg[k];if(k==='ants'){sim.cfg=cfg;sim.makeAnts()}}})}
function layer(){return{food:showFood.checked,home:showHome.checked,ants:showAnts.checked,encounters:showEncounters.checked,heat:showHeat.checked}}
function stat(){let s=sim.snapshot(),secs=(sim.t/60)|0;stats.innerHTML=[['Agents',sim.ants.length],['Searching',sim.ants.length-s.carry],['Know food',s.know],['Carrying food',s.carry],['Food delivered',s.delivered],['Knowledge exchanges',s.exchanges],['Explored area',s.explored.toFixed(1)+'%'],['Simulation ticks',sim.t]].map(v=>`<div class='stat'><span>${v[0]}</span><b>${v[1]}</b></div>`).join('');phase.textContent=!sim.running?'PAUSED':s.know<sim.ants.length*.15?'CHAOS / EXPLORATION':s.know<sim.ants.length*.6?'DISCOVERY / RELAY':'EMERGENT ORDER'}
function loop(ts){let dt=ts-last;last=ts;if(dt<80){for(let i=0;i<2;i++)sim.tick()}renderer.draw(layer());stat();requestAnimationFrame(loop)}
start.onclick=()=>sim.running=true;pause.onclick=()=>sim.running=false;reset.onclick=()=>sim.reset();destroy.onclick=()=>{world.destroyDominant();};csv.onclick=()=>{let rows=['time,delivered,exchanges,know,carry,explored',...sim.stats.history.map(o=>Object.values(o).join(','))];let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='coa-results.csv';a.click()};
let drawing=false;function act(e){let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,t=tool.value;if(t==='obstacle')world.paint(x,y,true);if(t==='erase')world.paint(x,y,false);if(t==='food'){world.food.x=x;world.food.y=y}if(t==='nest'){world.nest.x=x;world.nest.y=y}}
canvas.onpointerdown=e=>{drawing=true;act(e)};canvas.onpointermove=e=>{if(drawing&&(tool.value==='obstacle'||tool.value==='erase'))act(e)};window.onpointerup=()=>drawing=false;window.onresize=()=>renderer.resize();controls();init();requestAnimationFrame(loop);
